// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk1Js3823pXDz9hdIAKvYJr6xnjCx1MPg',
    appId: '1:72404136697:web:7b10fef559463dc570e828',
    messagingSenderId: '72404136697',
    projectId: 'palash-f5ac9',
    authDomain: 'palash-f5ac9.firebaseapp.com',
    storageBucket: 'palash-f5ac9.firebasestorage.app',
    measurementId: 'G-SF1XKDHF7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxS4RfdvhnGLCoVPqLvSxTGNNBuzCiFgw',
    appId: '1:72404136697:android:3fb147b1d40931bf70e828',
    messagingSenderId: '72404136697',
    projectId: 'palash-f5ac9',
    storageBucket: 'palash-f5ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEjz6c0eoABuACQTsiWdC9DbXRz_CFBRQ',
    appId: '1:72404136697:ios:8453a2182fee82b470e828',
    messagingSenderId: '72404136697',
    projectId: 'palash-f5ac9',
    storageBucket: 'palash-f5ac9.firebasestorage.app',
    iosBundleId: 'org.palash.app.palashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEjz6c0eoABuACQTsiWdC9DbXRz_CFBRQ',
    appId: '1:72404136697:ios:8453a2182fee82b470e828',
    messagingSenderId: '72404136697',
    projectId: 'palash-f5ac9',
    storageBucket: 'palash-f5ac9.firebasestorage.app',
    iosBundleId: 'org.palash.app.palashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk1Js3823pXDz9hdIAKvYJr6xnjCx1MPg',
    appId: '1:72404136697:web:0d1c1c2c75b91d7270e828',
    messagingSenderId: '72404136697',
    projectId: 'palash-f5ac9',
    authDomain: 'palash-f5ac9.firebaseapp.com',
    storageBucket: 'palash-f5ac9.firebasestorage.app',
    measurementId: 'G-4W2BHZZLYP',
  );
}
