// GENERATED FILE: Mapping of image keys to asset paths

const Map<String, String> imageAssetMap = {
  // Animals & Birds
  'cat': 'assets/default_content/images/animals/cat.png',
  'cow': 'assets/default_content/images/animals/cow.png',
  'dog': 'assets/default_content/images/animals/dog.png',
  'elephant': 'assets/default_content/images/animals/elephant.png',
  'fish': 'assets/default_content/images/animals/fish.png',
  'goat': 'assets/default_content/images/animals/goat.png',
  'horse': 'assets/default_content/images/animals/horse.png',
  'rabbit': 'assets/default_content/images/animals/rabbit.png',
  'tiger': 'assets/default_content/images/animals/tiger.png',
  'bird': 'assets/default_content/images/animals/bird.png',
  'sheep': 'assets/default_content/images/animals/sheep.png',
  'lion': 'assets/default_content/images/animals/lion.png',
  'monkey': 'assets/default_content/images/animals/monkey.png',
  'deer': 'assets/default_content/images/animals/deer.png',
  'bear': 'assets/default_content/images/animals/bear.png',
  'duck': 'assets/default_content/images/animals/duck.png',
  'pigeon': 'assets/default_content/images/animals/pigeon.png',
  'parrot': 'assets/default_content/images/animals/parrot.png',
  'crow': 'assets/default_content/images/animals/crow.png',
  'myna': 'assets/default_content/images/animals/myna.png',
  'peacock': 'assets/default_content/images/animals/peacock.png',
  'cuckoo': 'assets/default_content/images/animals/cuckoo.png',
  'owl': 'assets/default_content/images/animals/owl.png',
  'eagle': 'assets/default_content/images/animals/eagle.png',
  'hawk': 'assets/default_content/images/animals/hawk.png',
  'kite': 'assets/default_content/images/animals/kite.png',
  'swan': 'assets/default_content/images/animals/swan.png',

  // Classroom
  'blackboard': 'assets/default_content/images/classroom/blackboard.png',
  'book': 'assets/default_content/images/classroom/book.png',
  'chair': 'assets/default_content/images/classroom/chair.png',
  'desk': 'assets/default_content/images/classroom/desk.png',
  'eraser': 'assets/default_content/images/classroom/eraser.png',
  'pencil': 'assets/default_content/images/classroom/pencil.png',
  'school_bag': 'assets/default_content/images/classroom/school_bag.png',
  'ruler': 'assets/default_content/images/classroom/ruler.png',

  // Fruits
  'apple': 'assets/default_content/images/fruits/apple.png',
  'banana': 'assets/default_content/images/fruits/banana.png',
  'grapes': 'assets/default_content/images/fruits/grapes.png',
  'guava': 'assets/default_content/images/fruits/guava.png',
  'mango': 'assets/default_content/images/fruits/mango.png',
  'orange': 'assets/default_content/images/fruits/orange.png',
  'papaya': 'assets/default_content/images/fruits/papaya.png',
  'pomegranate': 'assets/default_content/images/fruits/pomegranate.png',
  'watermelon': 'assets/default_content/images/fruits/watermelon.png',
  'coconut': 'assets/default_content/images/fruits/coconut.png',
  'pineapple': 'assets/default_content/images/fruits/pineapple.png',
  'lemon': 'assets/default_content/images/fruits/lemon.png',
  'lychee': 'assets/default_content/images/fruits/lychee.png',

  // Vegetables
  'brinjal': 'assets/default_content/images/vegetables/brinjal.png',
  'carrot': 'assets/default_content/images/vegetables/carrot.png',
  'cauliflower': 'assets/default_content/images/vegetables/cauliflower.png',
  'onion': 'assets/default_content/images/vegetables/onion.png',
  'potato': 'assets/default_content/images/vegetables/potato.png',
  'tomato': 'assets/default_content/images/vegetables/tomato.png',
  'radish': 'assets/default_content/images/vegetables/radish.png',
  'ladyfinger': 'assets/default_content/images/vegetables/ladyfinger.png',

  // Mathematics
  'number_1': 'assets/default_content/images/mathematics/number_1.png',
  'number_2': 'assets/default_content/images/mathematics/number_2.png',
  'number_3': 'assets/default_content/images/mathematics/number_3.png',
  'number_4': 'assets/default_content/images/mathematics/number_4.png',
  'number_5': 'assets/default_content/images/mathematics/number_5.png',
  'number_6': 'assets/default_content/images/mathematics/number_6.png',
  'number_7': 'assets/default_content/images/mathematics/number_7.png',
  'number_8': 'assets/default_content/images/mathematics/number_8.png',
  'number_9': 'assets/default_content/images/mathematics/number_9.png',
  'number_10': 'assets/default_content/images/mathematics/number_10.png',
  'circle': 'assets/default_content/images/mathematics/circle.png',
  'diamond': 'assets/default_content/images/mathematics/diamond.png',
  'oval': 'assets/default_content/images/mathematics/oval.png',
  'triangle': 'assets/default_content/images/mathematics/triangle.png',
  'star': 'assets/default_content/images/mathematics/star.png',
  'square': 'assets/default_content/images/mathematics/square.png',
  'rectangle': 'assets/default_content/images/mathematics/rectangle.png',
  'plus': 'assets/default_content/images/mathematics/plus.png',
  'minus': 'assets/default_content/images/mathematics/minus.png',
  'division': 'assets/default_content/images/mathematics/division.png',
  'multiply': 'assets/default_content/images/mathematics/multiply.png',

  // Colors
  'black': 'assets/default_content/images/colors/black.png',
  'blue': 'assets/default_content/images/colors/blue.png',
  'green': 'assets/default_content/images/colors/green.png',
  'orange_color': 'assets/default_content/images/colors/orange.png',
  'pink': 'assets/default_content/images/colors/pink.png',
  'red': 'assets/default_content/images/colors/red.png',
  'white': 'assets/default_content/images/colors/white.png',
  'yellow': 'assets/default_content/images/colors/yellow.png',
  'purple': 'assets/default_content/images/colors/purple.png',
  'brown': 'assets/default_content/images/colors/brown.png',
};
